const EPSILON_SYMBOL = 'ε';
const EPSILON_IN_CFG = '';
const NON_TERMINAL_SYMBOLS_LIMIT = 25;
const DOLLAR_SYMBOL = '$';
const TURING_MACHINE_MAX_STEP_NUM = 200;
const DFA_TYPE = "DFA";
const NFA_TYPE = "NFA";
const PDA_TYPE = "PDA";
const TM_TYPE = "TM";

export { EPSILON_SYMBOL, EPSILON_IN_CFG, NON_TERMINAL_SYMBOLS_LIMIT, DOLLAR_SYMBOL, TURING_MACHINE_MAX_STEP_NUM, DFA_TYPE, NFA_TYPE, PDA_TYPE, TM_TYPE };
