const EPSILON_SYMBOL = '#';
const EPSILON_IN_CFG = '';
const NON_TERMINAL_SYMBOLS_LIMIT = 25;
const DOLLAR_SYMBOL = '$';

export { EPSILON_SYMBOL, EPSILON_IN_CFG, NON_TERMINAL_SYMBOLS_LIMIT, DOLLAR_SYMBOL };